# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

image: maven:3.8.3-jdk-11

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:
  - build 
  - test
  - package
  - deploy
  - notify


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only:
    - dev
    - master
    - merge_requests
    - /^release\/.*$/
  except:
    - tags
  script:
    - 'mvn compile'
  cache:
    paths:
      - ./target
      - ./.m2

unit-test-job:   # This job runs in the test stage.
  stage: test
  only:
    - dev
    - master
    - merge_requests
    - /^release\/.*$/
  except:
    - tags
  script:
    - 'mvn test'
  cache:
    paths:
      - ./target
      - ./.m2


package-job:   # This job also runs in the test stage.
  stage: package
  only:
    - master
    - /^release\/.*$/
  except:
    - tags
  script:
    - 'mvn package -Dmaven.test.skip=true'
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
